# Generated by Django 4.0.3 on 2022-06-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='langtolearn',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
